# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('tf_case', models.CharField(max_length=50)),
                ('action_discription', models.TextField()),
                ('environment', models.CharField(max_length=100)),
                ('request_duration', models.CharField(max_length=50)),
                ('duration', models.CharField(default='0:00:00', max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=100)),
                ('status', models.CharField(default='Ready', max_length=50)),
                ('progress', models.TextField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
