# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planTable',
        ),
    ]
