productlist=["iwhale2","whale2","isharkl2","sharkl2","sharkLJ1","whaleK","Other"]
statuslist=["wait for bitfile","wait for SW","wait for zebu","suspend","ongoing","close"]
acceptancelist=["Yes","No"]
city_list=["JC","SH","BJ"]
environment_list=["Zebu-JC","Zebu-SPRD","Hybrid"]