# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('project', models.CharField(choices=[('prj1', 'iwhale2'), ('prj2', 'other')], max_length=100)),
                ('classification', models.CharField(choices=[('classify1', 'Function'), ('classify2', 'Misc'), ('classify3', 'Performance'), ('classify4', 'Power'), ('classify5', 'Kernel'), ('classify6', 'Other')], max_length=100)),
                ('module', models.CharField(choices=[('module1', 'APPS'), ('module2', 'BSP'), ('module3', 'MM'), ('module4', 'Modem'), ('module5', 'Power'), ('module6', 'Stability'), ('module7', 'Kernel'), ('module8', 'Graphics'), ('module9', 'DDR'), ('module10', 'WCN')], max_length=100)),
                ('tf_case', models.CharField(choices=[('tf1', 'option1'), ('tf2', 'option2')], max_length=50)),
                ('action_discription', models.TextField()),
                ('environment', models.CharField(choices=[('env1', 'Zebu'), ('env2', 'Hybrid')], max_length=100)),
                ('request_duration', models.CharField(choices=[('rq_dur1', '12H'), ('rq_dur2', '24H'), ('rq_dur3', '36H'), ('rq_dur4', '48H'), ('rq_dur5', '60H'), ('rq_dur6', '72H'), ('rq_dur7', '84H'), ('rq_dur8', '96H'), ('rq_dur9', '108H'), ('rq_dur10', '120H')], max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('level1', 'High'), ('level2', 'Normal'), ('level3', 'Low')], max_length=100)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
