# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_requesttable_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='duration',
            field=models.CharField(default='0:00:00', max_length=50),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='progress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='status',
            field=models.CharField(default='wait for zebu', max_length=50),
        ),
    ]
