# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20160317_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='acceptance',
            field=models.CharField(default='false', max_length=20),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='close_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='daily_duration',
            field=models.CharField(default='24H', max_length=100),
        ),
    ]
