# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20160514_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='acceptance',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
