# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20160520_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='acceptance',
            field=models.CharField(choices=[('unaccept', 'No'), ('accept', 'Yes')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='request_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
