# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20160524_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='daily_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
