# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('spm', models.CharField(max_length=50)),
                ('daily_reporter', models.CharField(max_length=50)),
                ('file_link', models.TextField()),
            ],
        ),
    ]
