# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='is_daily_report',
            field=models.CharField(default='true', max_length=20),
        ),
    ]
